"""Add drug inventory

Revision ID: 3938f46ba006
Revises: 0030d4296f47
Create Date: 2026-06-04 19:46:06.909801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3938f46ba006'
down_revision = '0030d4296f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_inventory',
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('dosage_form', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('drug_id')
    )
    with op.batch_alter_table('drug_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drug_inventory_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drug_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drug_inventory_name'))

    op.drop_table('drug_inventory')
    # ### end Alembic commands ###
